// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenuePro.API.Data;

#nullable disable

namespace VenuePro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404060054_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenuePro.API.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("VenuePro.API.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("VenuePro.API.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatalogId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CustomPrice")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatalogId = "e1",
                            Category = "entrance",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "🎫",
                            Name = "Adult Ticket",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            CatalogId = "e2",
                            Category = "entrance",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "🧒",
                            Name = "Child Ticket",
                            Price = 120m
                        },
                        new
                        {
                            Id = 3,
                            CatalogId = "e3",
                            Category = "entrance",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "👴",
                            Name = "Senior Ticket",
                            Price = 150m
                        },
                        new
                        {
                            Id = 4,
                            CatalogId = "e4",
                            Category = "entrance",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "⭐",
                            Name = "VIP Pass",
                            Price = 750m
                        },
                        new
                        {
                            Id = 5,
                            CatalogId = "e5",
                            Category = "entrance",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "👥",
                            Name = "Group (10+)",
                            Price = 180m
                        },
                        new
                        {
                            Id = 6,
                            CatalogId = "d1",
                            Category = "donation",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "🥉",
                            Name = "Bronze Donor",
                            Price = 100m
                        },
                        new
                        {
                            Id = 7,
                            CatalogId = "d2",
                            Category = "donation",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "🥈",
                            Name = "Silver Donor",
                            Price = 500m
                        },
                        new
                        {
                            Id = 8,
                            CatalogId = "d3",
                            Category = "donation",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "🥇",
                            Name = "Gold Donor",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 9,
                            CatalogId = "d4",
                            Category = "donation",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "💎",
                            Name = "Platinum Donor",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 10,
                            CatalogId = "d5",
                            Category = "donation",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = true,
                            Icon = "❤️",
                            Name = "Custom Donation",
                            Price = 0m
                        },
                        new
                        {
                            Id = 11,
                            CatalogId = "s1",
                            Category = "selling",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "👕",
                            Name = "Museum T-Shirt",
                            Price = 499m
                        },
                        new
                        {
                            Id = 12,
                            CatalogId = "s2",
                            Category = "selling",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "☕",
                            Name = "Souvenir Mug",
                            Price = 199m
                        },
                        new
                        {
                            Id = 13,
                            CatalogId = "s3",
                            Category = "selling",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "🖼️",
                            Name = "Art Print",
                            Price = 350m
                        },
                        new
                        {
                            Id = 14,
                            CatalogId = "s4",
                            Category = "selling",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "📖",
                            Name = "Guidebook",
                            Price = 150m
                        },
                        new
                        {
                            Id = 15,
                            CatalogId = "s5",
                            Category = "selling",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "🍿",
                            Name = "Snack Combo",
                            Price = 120m
                        },
                        new
                        {
                            Id = 16,
                            CatalogId = "s6",
                            Category = "selling",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = false,
                            Icon = "🔑",
                            Name = "Premium Keychain",
                            Price = 99m
                        });
                });

            modelBuilder.Entity("VenuePro.API.Models.BillItem", b =>
                {
                    b.HasOne("VenuePro.API.Models.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("VenuePro.API.Models.Bill", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
